// src\engine\content\generation-pools\station\names.ts

import { SPECIES_ID, type SpeciesId } from '../../../defs/species';

export const STATION_NAME_POOLS_BY_SPECIES = {
    [SPECIES_ID.HUMAN]: [
        'Station Morrow',
        'Port Ansel',
        'Vesta Relay',
        'Kappa Dock',
        'New Rindle Transfer',
        'Bureau Annex 14',
        'Tollman Orbital',
        'Greyford Station',
        'Lumen Yard',
        'Civic Dock 9',
        'Harrowgate Relay',
        'Old Sagan Port',
        'Marbleton Station',
        'Outer Ward Annex',
        'Bastion Transfer',
        'Pike Administrative Dock',
        'Larkspur Orbital',
        'Redfield Customs',
        'Delta Filing Post',
        'Mason Belt Station',
    ],

    [SPECIES_ID.ALIEN]: [
        'Ool-Neth Relay',
        'Kzzar Dock',
        'Vek-Tal Node',
        'Narroth Spindle',
        'Ulvek Transfer',
        'Zuun-Tar Annex',
        'Mekkaal Port',
        'Thol Varn Station',
        'Nesh-Or Customs',
        'Vrakka Relay',
        'Yol-Teth Dock',
        'Korrun Orbital',
        'Azzek Junction',
        'Tuun-Maal Exchange',
        'Velkorr Station',
        'Narroth Minor',
        'Ghaal-7 Intake',
        'Orru Administrative Ring',
        'Tekk-Voss Dock',
        'Muunth Relay',
        'Zel-Orr Transfer',
        'Varnok Annex',
        'Esh-Tuun Node',
        'Kaalvek Station',
        'Ruunth Customs',
        'Ool-Varr Dock',
        'Nekkal Spindle',
        'Voss-Teth Relay',
        'Gorrun Waystation',
        'Ulthak Port Authority',
    ],
} satisfies Record<SpeciesId, readonly string[]>;
